### ISSUE TITLE
Cannot deconstuct error when openning the MUI VIdeo Uploader Page

### ISSUE THREAD

**Issue by mengnans** [muxinc/strapi-plugin-mux-video-uploader#66] opened 2023-07-19 06:34 UTC
I followed the installation instruction but I am getting this error when openning the MUX Video Uploader tab from the strapi admin.
![image](https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/20500503/fb2ee713-2316-4699-9061-5f6defeec593)

**Comment by erikpena** [comment] 2023-08-18 23:43
Hello @mengnans,
Thank you for filing this issue with us.  I just took a look at the codebase for our plugin and am not seeing any references to `allPermissions`.

I had also just set up a fresh instance of Strapi to see if there was maybe a regression that was introduced but hadn't experienced this issue in that case either.  What version of Strapi and the Mux Video Uploader plugin are you using?

Thank you,

**Comment by mmcc** [comment] 2023-12-16 00:29
Closing this since we never heard back, but if anyone is running into this please ping this thread or open a new issue.

**Closed by mmcc** 2023-12-16 00:29 UTC
